stefanjudis/perf-tooling

data/slides/useful-performance-metrics.json

Added slides from my talk “Useful performance metrics”. Closes #351

Added talk "Useful performance metrics" 

---

templates/partials/head.tpl

fix meta description

---

data/tools/yellow-lab-tools.json

Hi there!
YLT v1.1.0 is out, with several ways to automate the runs: a CLI, an NPM module and an API.

Update Yellow Lab Tools

---

data/tools/keepfast.json

very promising tool by @davidsonfellipe for integrating multiple performance indicators in a single interface

add Keepfast to tools

---

data/tools/sitespeed.json

Hey Stefan, added the link to the node module and that sitespeed also can output TAP.
Best
Peter

Added node module & TAP info

---

app.js
data/articles/going-beyond-onload.json
data/articles/high-performance-animations.json
data/articles/performance-impact-of-popular-javascript-mvc-frameworks.json
data/books/using-webpagetest.json
data/videos/what-makes-mobile-websites-tick-how-do-we-make-them-faster.json
templates/partials/authors/images.tpl
templates/partials/authors/names.tpl
templates/partials/lists/articles.tpl
templates/partials/lists/books.tpl
templates/partials/lists/slides.tpl
templates/partials/lists/videos.tpl

@marcobiedermann 
will make final check in master

Feature/332 multiple authors - fix #332

---

data/tools/dimensio.json

As discussed in #473, thank you. Hopefully the description doesn't read too much like an advert :)
This does not include any paid/isPaid attribute as the method for doing this is still under discussion in #18.
Cheers,
Lovell

Add dimens.io service

---

data/tools/css-stats.json

add grunt, gulp and node modules

---

data/tools/grunticon.json

Added grunticon from Filament Group (http://www.grunticon.com/) as a tool.

Added grunticon to tools.

---

data/articles/http2-for-a-faster-web.json

add "HTTP/2 for a Faster Web" article - fix #535

---

templates/index.tpl

Teaser book section at start page

book section & links on section titles to respective pages

---

data/tools/cssnano.json

cssnano is a modular minifier built on top of the PostCSS ecosystem - uses the same parser as autoprefixer, and supports advanced optimisations such as custom identifier compression, adjacent selector merging and others.
https://github.com/ben-eb/cssnano

Add cssnano.

---

data/tools/ruby-jmeter.json

A Ruby based DSL for building JMeter test plans.

adds ruby-jmeter gem

---

data/tools/yellow-lab-tools.json

Add grunt-yellowlabtools

---

data/articles/gulp-local-psi.json

add article "Setting up PageSpeed Insights to test Performance locally via Gulp" - fix #732

add article "Setting up PageSpeed Insights to test Performance

---

data/tools/webponize.json

I crafted [a tool for Mac](https://github.com/1000ch/webponize) which converts images into WebP.

add a tool "WebPonize"

---

data/articles/introduction-to-webp.json

I wrote up [an article](https://medium.com/@1000ch/introduction-to-webp-b593dfe1d1d1) about WebP by Google.

add an article "Introduction to WebP"

---

data/articles/we-should-optimize-images.json

I wrote up [an article](https://medium.com/@1000ch/we-should-optimize-images-8435760e0ec9) about image optimization. :)

add an article "We should optimize images"

---

data/articles/high-performance-images-beautiful-shouldnt-mean-slow.json

"High Performance Images: Beautiful Shouldn’t Mean Slow"

add article - fix #780 

---

data/tools/imgix.json

I've also added the `Java` library. I open up a ticket for adding a new icon to the tools.

add "imgix" tool - fix #769

---

data/articles/perfaudit-materialup.json

https://github.com/stefanjudis/perf-tooling/issues/816

added article 'Performance Audit of Materialup.com'

---

data/slides/performance-beyond-page-load.json

Adding slides for the talk "Performance beyond page load" presented at jQuery Conference.

Adding slides for "Performance beyond page load"

---

data/articles/rail-user-centric-model-performance.json

article "Introducing RAIL: A User-Centric Model For Performance" by Paul Irish and Paul Lewis

fix #861 - add article "Introducing RAIL"

---

data/tools/inspectIT.json

add inspectIT.json at data/tools directory

add inspectIT.json at data/tools directory

---

data/tools/stylestats.json

Add a chrome extension of StyleStats

---

data/slides/what-we-talk-about-when-we-talk-about-web-performance.json
data/videos/what-we-talk-about-when-we-talk-about-web-performance.json

Feature: #1072 "What We Talk About When We Talk About Web Performance"

---

data/slides/statistics-of-web-performance-measurement-and-anomaly-detection.json

"Statistics of Web Performance Measurement and Anomaly Detection" slideshow

fix #1070 - add "Statistics of Web Performance"

---

.github/CONTRIBUTING.md
templates/index.tpl

🐛  fix links to the contributing.md and update the document

---

data/articles/preload-prefetch-and-priorities-in-chrome.json

📝 add "Preload, prefetch and priorities in Chrome" -  fix #1249

---

data/articles/building-performant-expand-and-collapse-animations.json

📝 add performant expand and collapse animations - fix #1252

---

lib/helper/youtube.js

prevent app crash on missing youtube stats - fix #1254

---

data/tools/pwmetrics.json

Hy guys. We've released a new version of [pwmetrics](https://github.com/paulirish/pwmetrics) with a lot of features. Don't you mind have this tool in your list?

:memo: add pwmetrics tool

---

data/slides/improve-performance-with-progressive-web-metrics.json

Hey guys 👋 . I had a talk this weekend at conf in Ukraine talking about perf. I considered you might be interesting to have this presentation here :) 
Thanks.

Add "Improve performance with Progressive Web Metrics" presentation

---

data/articles/deploying-brotli-for-static-content.json

 📝 add "Deploying Brotli for static content" - fix #1258

---

data/tools/device-timing.json

📝 add deviceTimin -fix #1260

---

data/articles/h2-is-tougher-than-i-thought.json

📝 add "H2 is tougher than I thought" - fix #1265

---

data/videos/css-and-the-first-meaningful-paint.json

📝 add "CSS and the first meaningful paint" -  fix #1264

---

data/articles/making-photos-smaller-without-quality-loss.json

📝 add "Making Photos smaller without quality loss" - fix #1268

---

data/videos/leveraging-the-metrics-that-most-affect-user-experience.json

📝 add "Leveraging the Metrics that Most Affect UX" - fix #1270

---

data/slides/empathy-and-web-performance.json
data/videos/empathy-and-web-performance.json

📝 add "Empathy and Web Performance" - fix #1245

---

data/slides/reliably-measuring-responsiveness-in-the-wild.json

📝 add "Reliably measuring responsiveness in the wild - fix #1273

---

data/tools/bundlesize.json

📝 add “bundlesize” - fix #1275

---

data/articles/performance-and-resilience-stress-testing-third-parties.json

📝 add "Performance and Resilience" - fix #1279

---

data/articles/the-critical-request.json

📝 add "the critical request" -  fix #1281

---

data/slides/the-state-of-the-web.json

📝 Add "The state of the web" - fix #1284

---

data/tools/lozad.json

added lozad.js in tools section

:memo: added lozad.js in tools

---

data/tools/compare.json

📝 add compare - fix #1287

---

data/articles/performance-metrics-whats-this-all-about.json

📝 add "Performance metrics what's it all about" - fix #1290

---

data/tools/size-limit.json

📝 add "Size Limit" tool - fix #1295

---

data/slides/why-fast-matters.json

📝 add "Why fast matters" slides - fix #1297

---

data/articles/improving-performance-with-the-paint-timing-api.json

📝 add "Improving Performance with the Paint Timing API" article

---

data/articles/how-3rd-party-scripts-can-be-performant-citizens-on-the-web.json

📝 add "How 3rd party scripts can be performant" - fix #1304

---

data/videos/http2-what-no-one-is-telling-you.json

📝 add "http/2 - what no one is telling you" - fix #1310

---

data/tools/glyphhanger.json

📝 add glyphhanger - fix #1312

---

data/articles/the-cost-of-javascript.json

📝 add "The cost of JavaScript" - fix #1307

---

data/videos/fast-by-default.json

📝 add "fast by default" - fix #1302

---

lib/helper/twitter.js

Hotfix: Twitter

---

data/tools/imgix.json

Hotfix: Imgix

---

data/tools/css-triggers.json

Hotfix: CSS triggers

---

data/videos/what-we-talk-about-when-we-talk-about-web-performance.json

Closes issue https://github.com/stefanjudis/perf-tooling/issues/1323
Let me know if this is all correct.

:memo: Updates Patty Toland conf talk to newest edition

---

data/videos/you-dont-need-amp-for-that.json

📝 add "You don't need amp for that" - fix #1322

---

data/articles/http2-push-vs-http-preload.json

  📝 Add "Http/2 push vs http preload" - fix #1308

---

data/tools/subfont.json

📝 add "subfont" tool - fix #1316

---

data/slides/hardware-networks-performance-improving-page-perf.json

📝 add "Hardware, Networks, and Performance" slides - fix #1340

---

data/articles/optimize-your-mp4-video-for-better-performance.json

:memo: Optimize your MP4 video for better performance

---

data/articles/web-performance-fundamentals-what-is-the-speed-index.json

New blog post, for webperf beginners!

:memo: Web Performance Fundamentals: what is the Speed Index?

---

data/tools/web-font-loader.json
data/tools/woff2.json

:memo: add "woff2" - fix #1347

---

data/tools/node-clinic.json
data/tools/woff2.json

:memo: Add "node clinic"

---

data/tools/sloth.json

📝 add "Sloth" - fix #1350

---

data/articles/resourcetiming-visibility-third-party-scripts-ads-and-page-weight.json

📝 add "ResourceTiming Visibility: Third-Party Scripts, Ads and Page Weight" - fix #1352

---

data/slides/how-s-the-ux-on-the-web.json
data/videos/how-s-the-ux-on-the-web.json

📝 Add "how's the ux on the web, really?" - fix #1354

---

data/videos/data/videos/delta-conf-web-perf-webinar.json

:memo: Create delta-conf-web-perf-webinar.json

---

data/articles/the-business-value-of-site-speed-and-how-to-analyze-it-step-by-step.json

📝 The Business Value of Site Speed — And How to Analyze it Step by Step

---

data/tools/netinfo-monitor.json

📝 Add netinfo-monitor - fix #1359

---

data/tools/image-heap.json

📝 add image-heap - fix #1361

---

data/tools/speed-demon.json

Add speed-demon - fix #1365

---

data/articles/embedded-image-previews.json

Hey there,
Here is my latest article about web performance. Please change the commit message while merging to ensure my commit follows the guidelines.
Thanks a lot :)
Benedikt

:memo: add article about embedded image previews

---

data/articles/the-cost-of-javascript-2018.json
data/videos/the-cost-of-javascript-2018.json

📝 Add the cost of JavaScript

---

data/tools/treo.json

:memo: add Treo

---

data/articles/accurately-measuring-layout-on-the-web.json

Add "accurately measuring layout on the web"

---

data/articles/idle-until-urgent.json

Add "Idle until urgent" article

---

data/tools/imgbot.json

📝  add "ImgBot" tool

---

data/articles/tti-focusing-on-the-human-centric-metrics.json

📝 add "TTI human centric metrics" article

---

data/tools/squoosh.json

📝  add "Squoosh" tool

---

data/tools/speedrank.json

With Speedrank you get detailed audits about your website. We check the speed for your visitors and recommend improvements. Check also the websites of your competitors and take off in the point speed.

📝 add Speedrank

---

data/tools/debugbear.json

Front-end performance monitoring based on Lighthouse. Get an alert when something goes wrong, and access the information you need to fix the problem.

📝 Add DebugBear

---

data/books/web-performance-pocket-guide.json

Five Simple Steps closed several years ago and link to pocket guide wasn't working- updated with new link

:bug: Updated link to working version of Pocket Guide to Web Performance

---

data/articles/rendering-on-the-web.json

📝 add "Rendering on the web" article

---

data/slides/more-than-you-ever-wanted-to-know-about-resource-hints.json

Add " More Than You Ever Wanted to Know About Resource Hints"

---

data/videos/speed-at-scale-web-performance-tips-and-tricks-from-the-trenches.json

Add "Speed at Scale: Web Performance Tips and Tricks from the Trenches"

---

data/videos/demystifying-speed-tooling.json

📝add "Demystifying speed tooling"

---

data/tools/exthouse.json

Hi folks 👋 
Haven't contributed for a while. Recently we've released [Exthouse](https://github.com/treosh/exthouse) tool for measuring extensions impact on web performance. Hope there will be a spot for it in perf-tooling 🤗 
P.S.
Here's Exthouse report for Grammarly extension

📝 add "Exthouse" tool

---

data/articles/self-host-your-static-assets.json

Add "self-host your static assets"

---

data/articles/defer-scripts-to-speed-up-rendering.json

:memo: Defer scripts to speed up rendering

---

data/articles/google-speed-update-ranking-signal-mobile-searches.json

:memo Google Speed Update: a Speed Ranking Signal for Mobile Searches

---

data/articles/common-mistakes-in-tracking-speed.json
data/articles/core-web-vitals.json
data/articles/getting-started-with-performance.json
data/articles/lighthouse-changes-performance-score.json

This PR adds the following posts:
- [Everything You Have to Know About Core Web Vitals](https://calibreapp.com/blog/core-web-vitals)
- [5 Common Mistakes Teams Make When Tracking Performance](https://calibreapp.com/blog/common-mistakes-in-tracking-speed)
- [Lighthouse Changes How Performance Score is Calculated](https://calibreapp.com/blog/lighthouse-changes-scoring-algorithm)
- [Getting Started with Web Performance](https://calibreapp.com/blog/get-started-with-performance)
sorry for not using emojis in the commit messages @stefanjudis—I noticed that note after making the commits and didn't want to get myself into a github rebase funk situation 😅 I can redo if need be. also, feel free to cherry-pick specific articles if you don't think some are not relevant.
⚡

📝 Add recent posts on Vitals, LH6 scoring, getting started with perf guide + common mistakes in tracking speed
